spring:
  application:
    name: customer-service
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:customers
  jpa:
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
server:
  port: 9091
  error:
    include-stacktrace: never
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readinessstate:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG