spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customers
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/{segment},/api/v2/{segment}
        - id: prefixpath_route
          uri: https://example.org
          predicates:
            - Path=/test
          filters:
            - RedirectTo=302, https://spring.io

server:
  port: 9090
  error:
    include-stacktrace: never


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    root: INFO
    com:
      example: DEBUG
    org:
      springframework:
        cloud:
          gateway: TRACE

