spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/{segment}
server:
  port: 9090
  error:
    include-stacktrace: never


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    root: INFO
    com:
      example: DEBUG
    org:
      springframework:
        cloud:
          gateway: TRACE

