spring:
  cloud:
    gateway:
#      routes:
#        - id: http-bin
#          uri: https://httpbin.org
#          predicates:
#            - Path=/get
#          filters:
#            - AddResponseHeader=X-My-Header, Test
      metrics:
        enabled: true
        tags:
          path:
            enabled: true
  application:
    name: api-gateway
logging:
  level:
    org.springframework.cloud.gateway: trace

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
server:
  port: 9999